import NavBar from "@/components/navBar";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";

const JosefinSans = Josefin_Sans({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Eagle Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JosefinSans.className}>
        <NavBar />
        <main className="pt-16">{children}</main>
      </body>
    </html>
  );
}
